### ISSUE TITLE
Fake COM to real COM

### ISSUE THREAD

**Issue by yyokyfo** [tishion/potto#12]
What do you think about modifying Potto in a way that any valid Potto object is also a valid real MS COM object? This way, the same dll could be served as both Potto COM server and MS COM server. Is it something possible?

**Comment by tishion** [comment]
Hi @yyokyfo , thanks for your inspired question. Potto is only a minimal subset implementation of MS COM concept and it exposed the same IUnknown interface of the object, theoretically speaking you can consume the potto object in MS COM runtime as long as you can get the object instance created by potto. If you would like to try you can make some modification of Potto as follow instructions:
1. compile Potto with POTTO_USE_GUID enabled, because MS COM use real GUID but potto use string by default:
https://github.com/tishion/potto/blob/8f2b1d38ba09b60a059943426545abf25b03d489/include/potto/pottouuid.hpp#L19
2. change the UUID value of Potto::IUnknown({10000000-0000-0000-0000-000000000000}), you need change the UUID to the value which exactly the same with MS IUnknown({00000000-0000-0000-C000-000000000046}) :
https://github.com/tishion/potto/blob/8f2b1d38ba09b60a059943426545abf25b03d489/include/potto/pottointerface.hpp#L16
3. change the UUID value of Potto::IClassFactor({10000000-0000-0000-0000-100000000001})  to MS IClassFactory({0000001B-0000-0000-C000-000000000046}):
https://github.com/tishion/potto/blob/8f2b1d38ba09b60a059943426545abf25b03d489/include/potto/pottointerface.hpp#L48


4. then you should initialize and create potto object by Potto methods: 
initialize potto runtime
https://github.com/tishion/potto/blob/8f2b1d38ba09b60a059943426545abf25b03d489/include/potto/potto.h#L47

ceate instance and get interface
https://github.com/tishion/potto/blob/8f2b1d38ba09b60a059943426545abf25b03d489/include/potto/potto.h#L65
or
https://github.com/tishion/potto/blob/8f2b1d38ba09b60a059943426545abf25b03d489/include/potto/potto.h#L83


then you can pass the interface to MS COM runtime methods.

limitatios of Potto
- No complex apartment models
- No Dispatch supports
- No Windows registry available


Good luck~
