### ISSUE TITLE
Incorrectly force /utf-8 on Windows

### ISSUE THREAD

**Issue by iahung2** [tishion/potto#5]
/utf-8 is a MSVC-only switch that GCC and Clang (I'm not sure about Clang-Cl) don't understand.

**Comment by iahung2** [comment]
Since MSVC is Windows-only so MSVC also implied WINDOWS. No need for a nested if. Btw, the GCC and Clang I mentioned are not cross compilers. They are running on Windows and are based on MinGW.

**Comment by tishion** [comment]
Hi @iahung2 , I understand what you mean, but I think you'd better keep the WINDOWS definition check.

The following definitions are for target platform. 
WINDOW
LINUX
ANDROID
MACOSX
IOS


But MSVC/GCC/CLANG are for compilers

if you want to support compile Windows platform target with GCC/CLANG, you should add compiler check under WINDOWS block instead of replacing WINDOWS with MSVC/GCC/CLANG

**Comment by iahung2** [comment]
Checking for `WINDOWS` is redundant, as both MSVC and MinGW (this variable is to check for MinGW-based GCC/CLANG on Windows) are Windows-only compilers.

https://cmake.org/cmake/help/latest/variable/MSVC.html

https://cmake.org/cmake/help/latest/variable/MINGW.html

**Comment by iahung2** [comment]
Update: I understand your design decision. You want to make it clear what is the target platform. The latest code of you compiled fine on MSYS2 (UCRT64). I think my PR is not needed anymore. Thank you.
